### ISSUE TITLE
failed: Importing listener 'jiraissueopener' failed: Modules do not take arguments.

### ISSUE THREAD

**Issue by AgentVicman007** [andreagubellini/robotframework-jiraissueopener#3]
Hi,
We are currently getting the below error when the below command. Of-course I updated the username and password. Also I added the variables and filled them out accordingly.
robot --listener "jiraissueopener;testusername;mycoolpassword" mytests.robot

Please help

**Comment by andreagubellini** [comment]
hi @AgentVicman007, how did you install the library?

can you show me the output of `pip show robotframework-jiraissueopener`?

**Comment by AgentVicman007** [comment]
Hi @andreagubellini ,
Below is the output. Thanks for the help.

Name: robotframework-jiraissueopener
Version: 0.1.0.0
Summary: An automatic Jira issue opener for Robotframework
Home-page: https://github.com/andreagubellini/robotframework-jiraissueopener
Author: Andrea Gubellini
Author-email: agubellini@yahoo.com
License: UNKNOWN
Location: /Users/jc/Documents/BT/automation-rf/venv/lib/python3.8/site-packages
Requires: requests, robotframework
Required-by:

**Comment by AgentVicman007** [comment]
Hi @andreagubellini,

I'm running Robot Framework 4.1.2 (Python 3.8.2 on darwin). Do you think the issue might be related to the RF version I'm running?

Thanks for your help!

**Comment by andreagubellini** [comment]
hi @AgentVicman007 there's an issue with the latest release. I'll make some fixes then come back to you. I should be releasing the fix late today

**Comment by andreagubellini** [comment]
hi @AgentVicman007 this is resolved with the v0.2.0 release. Please be sure to check the updated README as some things are updated and different now.

I also managed to fix the issue so everything should work now, sorry for the long wait.

Let me know if this release solved your problems :)

**Comment by AgentVicman007** [comment]
Hi @andreagubellini ,
It works now. However, now I keep getting _401 Client Error: Unauthorized for url:_
Would you happen to know if I need to enable anything from JIRA UI? I noticed that the JIRA docs mention API token?
When I visit the url the console displays in a browser it returns 
_{"startAt":0,"maxResults":50,"total":0,"issues":[]}_

Thank you in advance

**Comment by andreagubellini** [comment]
Hi @AgentVicman007, are you using a token or the account's password?

Make sure the credentials are your username & your password, do not use a token! :)

**Comment by AgentVicman007** [comment]
Hi @andreagubellini                       
I’m using username and password
robot --Listener “jiraissueopener;MyUsername;Mypassword" Tests/jira.robot

Within the test I have the below 
*** Variables ***
${JIRA_PROJECT} =     https://myserver.atlassian.net/rest/api/2/
${JIRA_PROJECT_ID} =  185
${JIRA_ISSUE_TYPE} =  10896
${JIRA_PROJECT_KEY} =  CEW

The response 

==============================================================================
Jira                                                                          
==============================================================================
[ ERROR ] 401 Client Error: Unauthorized for url: https://myserver.atlassian.net/rest/api/2/search/?jql=project+%3D+%22CEW%22+AND+resolution+%3D+Unresolved+AND+summary+~+%22Jira%3A+Failed+test+Case+has+failed%22
Failed test Case :: This test fails. A jira issue will be opened.     | FAIL |
Title should have been 'test' but was 'Name'.
